#server:
#  port: 8010
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgres://ec2-34-236-87-247.compute-1.amazonaws.com:5432/dfoemj05v7elt6?autosave=always
    username: iebmmzhelyvrge
    password: 2c06a89d70b4878bfaa4278e9ff9888bd885b234d43381780eb21bedab7158a0
    #url: jdbc:mysql://localhost:3306/filmbuff
    #username: root
    #password: password
  jpa:
    show-sql: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
#    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  https://filmbuff-discovery.herokuapp.com/eureka