server:
  port: 8010
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/filmbuff
    username: root
    password: password
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
      